- package.json
Add [sideEffects](https://webpack.js.org/configuration/optimization/#optimizationsideeffects) config to facilitate tree shaking
> chore(sideeffects): deactivate sideeffects to facilitate tree shaking

- src/Toggle/Toggle.styles.ts
Fix clickable area in Firefox for Toggle component.
> fix(Toggle): clickable area in Firefox

- src/Button/Button.styles.ts
- src/Button/Button.tsx
- src/Button/constants.ts
- src/Checkbox/Checkbox.styles.ts
- src/Checkbox/Checkbox.tsx
- src/Radio/Radio.styles.ts
- src/Radio/Radio.tsx
- src/Typography/Typography.stories.tsx
- src/Typography/Typography.styles.ts
- src/Typography/Typography.test.tsx
- src/Typography/Typography.tsx
- src/Typography/constants.ts
- src/Typography/types.ts
BREAKING CHANGE: rename variants
> feat(Button)!: use Typography variants

- .github/workflows/chromatic.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/sonar.yml
- .github/workflows/tests.yml
- package-lock.json
- package.json
- src/Colors/Colors.stories.mdx
In this story every color in the theming palette is displayed alongside it’s hexadecimal number and it’s visual representation.
> feat: add colors documentation story

- package-lock.json
- src/Icon/Icon.stories.tsx
- src/Icon/Icon.styles.ts
- src/Icon/Icon.test.tsx
- src/Icon/Icon.tsx
- src/Icon/constants.ts
- src/Icon/index.ts
- src/Icon/types.ts
Add grid area to icon component depending on the size
> feat(icon): add grid area to icon component

- src/Box/Box.styles.ts
- src/Box/Box.tsx
- src/Box/types.ts
Added the flexGap prop to box that uses the CSS Style "gap".
> feat(Box): added flexGap prop

- src/Button/Button.stories.tsx
- src/Button/Button.styles.ts
- src/Button/utils.ts
Apply color to the icon, inside the button component, as the typography depending on the button variant
> feat(button): apply same color to icon and typography

- src/Spinner/Spinner.stories.tsx
- src/Spinner/Spinner.styles.ts
- src/Spinner/Spinner.tsx
- src/Spinner/types.ts
> feat(spinner): add colors to spinner

- src/Box/Box.styles.ts
- src/Box/Box.tsx
- src/Box/types.ts
Usage example:
```typescript
<Box display="flex">
<Box flexGrow={1} />
<Box flexShrink={0} />
<Box flexBasis='200px' />
</Box>
```
> feat(Box): more flexbox props

- package-lock.json
- package.json
- src/Tooltip/Tooltip.stories.tsx
- src/Tooltip/Tooltip.styles.ts
- src/Tooltip/Tooltip.test.tsx
- src/Tooltip/Tooltip.tsx
- src/Tooltip/index.ts
- src/Tooltip/types.ts
- src/index.ts
> feat(tooltip): create tooltip component

- src/Autocomplete/Autocomplete.stories.tsx
- src/Autocomplete/Autocomplete.styles.ts
- src/Autocomplete/Autocomplete.test.tsx
- src/Autocomplete/Autocomplete.tsx
- src/Autocomplete/index.ts
- src/Autocomplete/types.ts
- src/TextField/TextField.tsx
> feat(autocomplete): create autocomplete component

- src/TextArea/TextArea.tsx
- src/TextArea/types.ts
> feat: allow full height text area

- src/Popover/Popover.stories.tsx
- src/Popover/Popover.test.tsx
- src/Popover/types.ts
- src/Popover/usePopover.ts
Añadimos una nueva property para indicar si queremos que se cierre al hacer scroll
> feat: close popover on scroll

- src/Tabs/Tabs.stories.tsx
- src/Tabs/Tabs.styles.ts
- src/Tabs/Tabs.tsx
> fix(tabs): fix story for tabs component

- src/Popover/Popover.stories.tsx
- src/Popover/PopoverContent.tsx
- src/Popover/types.ts
- src/Popover/usePopover.ts
Add usePortal prop `true` by default that determines if popover is mounted in a portal or as a sibling of the trigger.
> feat(Popover): usePortal prop

- src/Select/Select.stories.tsx
- src/Select/Select.tsx
- src/Select/types.ts
> feat(Select): add no results text prop

- src/components/banner/Banner.stories.tsx
- src/components/banner/Banner.styles.ts
- src/components/banner/Banner.tsx
- src/components/banner/Banner.types.ts
- src/components/banner/index.ts
- src/index.ts
- tsconfig.json
We use banners in different parts of our app; therefore, we have decided to publish a standard banner.
> feat: add banner component

- .github/workflows/chromatic.yml
- package-lock.json
- package.json
- src/components/breadcrumb/Breadbrumb.test.tsx
- src/components/breadcrumb/Breadcrumb.stories.tsx
- src/components/breadcrumb/Breadcrumb.styles.ts
- src/components/breadcrumb/Breadcrumb.tsx
- src/components/breadcrumb/Breadcrumb.types.ts
- src/components/breadcrumb/BreadcrumbLabel.tsx
- src/components/breadcrumb/BreadcrumbLabelContainer.tsx
- src/components/breadcrumb/BreadcrumbSeparator.tsx
- src/components/breadcrumb/index.ts
- src/index.ts
> feat(components): create breadcrumb component

- src/components/breadcrumb/BreadcrumbLabel.tsx
fix font-weight in breadcrumb component
> fix(breadcrumb): fix font weight in breadcrumb

- src/components/tabs/Tab.tsx
- src/components/tabs/Tabs.stories.tsx
- src/components/tabs/Tabs.styles.ts
- src/components/tabs/Tabs.tsx
Move the bottom line in the tabs component to the tabs container level so that it takes the entire available width
> fix(tabs): bottom line at the container level so that it takes entire width

- src/components/breadcrumb/Breadcrumb.styles.ts
- src/components/breadcrumb/Breadcrumb.tsx
fix ellipsis in responsive mode
> fix(breadcrumb): fix ellipsis in responsive mode

- README.md
- package-lock.json
- package.json
- src/components/stepper/Stepper.stories.tsx
- src/components/stepper/Stepper.styles.ts
- src/components/stepper/Stepper.test.tsx
- src/components/stepper/Stepper.tsx
- src/components/stepper/Stepper.types.tsx
- src/components/stepper/StepperLabel.styles.ts
- src/components/stepper/StepperLabel.tsx
- src/components/stepper/index.ts
- src/index.ts
Create stepper component
https://638dbcc7869db28ad2ebd96d-nygxvjjagh.chromatic.com/?path=/docs/components-stepper--docs
> Stepper component

- src/components/text-area/TextArea.styles.ts
- src/components/text-area/TextArea.tsx
- src/components/text-area/TextArea.types.ts
add resize prop to textarea component
> feat(components): add resize to textarea

- package-lock.json
- package.json
- src/components/rich-text-editor/RichTextEditor.stories.tsx
- src/components/rich-text-editor/RichTextEditor.styles.ts
- src/components/rich-text-editor/RichTextEditor.test.tsx
- src/components/rich-text-editor/RichTextEditor.tsx
- src/components/rich-text-editor/RichTextEditor.types.ts
- src/components/rich-text-editor/RichTextEditor.utils.ts
- src/components/rich-text-editor/index.ts
- src/components/rich-text-editor/plugins/CodeHighlightPlugin.ts
- src/components/rich-text-editor/plugins/ToolbarPlugin.tsx
- src/index.ts
- src/shared/inputStyles.ts
Added RichTextEditor component with basic features using @lexical/react.
> feat: add rich text editor

- README.md
As a mistake of previous MR, commits were squashed and the resulting commit message didn't trigger a new version of the library. This MR is just to trigger a new version.
> TT-142: trigger release

- package-lock.json
- package.json
- src/components/chat/components/message-thread/components/Message.styles.ts
- src/components/chat/components/message-thread/components/Message.tsx
- src/components/rich-text-editor/RichTextEditor.stories.tsx
- src/components/rich-text-editor/RichTextEditor.test.tsx
- src/components/rich-text-editor/RichTextEditor.tsx
- src/components/rich-text-editor/RichTextEditor.types.ts
- src/components/rich-text-editor/index.ts
- src/components/rich-text-editor/plugins/MaxLengthPlugin.tsx
Added `maxLength` prop to `RichTextEditor`
> feat: add max length plugin

- src/components/dialog/Dialog.styles.ts
update zindex in dialog overlay
> fix(dialog): update zindex in dialog overlay

- package-lock.json
- package.json
This PR unifies the version of some dependencies used accross projects.
We will open new PRs in a while. Once this first project is released with a new version
> feat: unify dependencies

- package-lock.json
- package.json
- src/components/rich-text-editor/RichTextEditor.stories.tsx
- src/components/rich-text-editor/RichTextEditor.tsx
- src/components/sidebar/Sidebar.tsx
- src/components/text-area/TextArea.stories.tsx
- src/components/text-field/TextField.stories.tsx
- src/types/styled-components.d.ts
> test(lint): upgrade lint landbot package

- .github/workflows/release.yml
fix release workflow after creating toast component
> feat(toast): fix release workflow

- .github/workflows/build.yml
- package-lock.json
- package.json
- src/types/styled-components.d.ts
> fix(typecheck): add typecheck to ci

- src/components/dialog/Dialog.styles.ts
- src/components/dialog/DialogContent.tsx
- src/components/overlay/Overlay.stories.tsx
- src/components/overlay/Overlay.styles.ts
- src/components/overlay/Overlay.tsx
- src/components/overlay/index.ts
- src/components/toast/Toast.tsx
- src/components/toast/Toast.types.ts
- src/components/toast/ToastProvider.tsx
- create Overlay component
- use new Overlay component in Dialog component
- change the Toast component to add external custom styles
> feat(components): create overlay component

- src/components/overlay/Overlay.stories.tsx
- src/components/toast/Toast.stories.tsx
- src/components/toast/Toast.test.tsx
- src/components/toast/Toast.tsx
- src/components/toast/Toast.types.ts
> fix(components): allow more than one button in the toast action

- src/components/table/Table.HeaderCell.tsx
- src/components/table/Table.PopoverCell.tsx
- src/components/table/Table.TextCell.tsx
- src/components/table/Table.stories.tsx
- src/components/table/Table.test.tsx
- src/components/table/Table.types.ts
Refactors table component to use children on cells. Otherwise we cannot fullfill the requirements on Figma without doing custom cells every time
> MAN-1267: refactor table component to use children

- src/components/select/Select.styles.ts
- src/components/select/Select.tsx
- src/components/select/Select.types.ts
- src/components/table/Table.PaginationFooter.test.tsx
- src/components/table/Table.PaginationFooter.tsx
- src/components/table/Table.stories.tsx
- src/components/table/index.ts
- src/components/text-field/TextField.styles.ts
- src/components/text-field/TextField.tsx
- src/components/text-field/TextField.types.ts
Adds a table pagination footer component
> MAN-1267: add table pagination footer component

- src/components/select/Select.tsx
- src/components/select/Select.types.ts
- src/components/table/Table.PaginationFooter.style.tsx
- src/components/table/Table.PaginationFooter.test.tsx
- src/components/table/Table.PaginationFooter.tsx
- src/components/table/Table.stories.tsx
Modifies table footer to add an optional page size selector
> feat: add rows per page

- src/components/select/Select.tsx
- src/components/select/Select.types.ts
- src/components/table/Table.PaginationFooter.style.tsx
- src/components/table/Table.PaginationFooter.tsx
- src/components/table/Table.stories.tsx
> Improve table footer styles

- src/components/table/Table.PaginationFooter.style.tsx
It seems semantic did not made. a release on the las merge. This is just a foo pr to retriger
> fix: force semantic release

- src/components/table/Table.BodySkeleton.styles.ts
- src/components/table/Table.BodySkeleton.test.tsx
- src/components/table/Table.BodySkeleton.tsx
- src/components/table/Table.stories.tsx
- src/components/table/index.ts
Adds a table skeleton for loading pages
> feat: add table skeleton

- src/components/table/Table.PopoverCell.tsx
- src/components/table/Table.styles.ts
> fix: dom elements

- src/components/button/Button.constants.ts
- src/components/button/Button.styles.ts
- src/components/button/Button.tsx
- src/components/button/Button.types.ts
- src/components/button/Button.utils.ts
- src/components/menu/Menu.stories.tsx
- src/components/menu/Menu.styles.ts
- src/components/menu/Menu.tsx
- src/components/menu/MenuButton.tsx
- src/components/menu/index.ts
- src/components/typography/Typography.types.ts
- src/index.ts
- Adds a new menu component. [Fima](https://www.figma.com/design/04e06uzVIOJzrIBpbcOquL/LUI-Design-System?node-id=5257-6188&node-type=canvas&t=KacJp40rd8sqmV6S-0)
- Adds new variant  and color for buttons. [Fima](https://www.figma.com/design/04e06uzVIOJzrIBpbcOquL/LUI-Design-System?node-id=886-412&node-type=frame&t=R7dzVMULz6S44H9O-0)
> feat: add menu component and button menu-item variant.

- src/components/checkbox/Checkbox.test.tsx
- src/components/table/Table.Header.tsx
- src/components/table/Table.Row.test.tsx
- src/components/table/Table.SelectableIndexCell.tsx
- src/components/table/Table.stories.tsx
- src/components/table/useTablePageSelector.test.tsx
- src/components/table/useTablePageSelector.tsx
Fixing typo and improving typing
> fix: type on toggle methods

- src/components/menu/index.ts
Add missing export to be able to use menu buttons on daisho-3
> feat: add missing export

- src/components/menu/Menu.stories.tsx
- src/components/menu/MenuButton.tsx
No estuve fino con TS aquí 🤦 Podía pasar las props hacia abajo pero TS se quejaba
> fix: improve button typing

- src/components/button/Button.utils.ts
Fixes background color for error button
> fix: varian color on button component

- src/components/autocomplete/AutoCompleteOptions.tsx
- src/components/autocomplete/Autocomplete.stories.tsx
- src/components/autocomplete/Autocomplete.test.tsx
- src/components/autocomplete/Autocomplete.tsx
- src/components/autocomplete/Autocomplete.types.ts
- src/components/autocomplete/AutocompleteOptions.styles.ts
Allow to customize autocomplete
> feat: allow to customize autocomplete

- src/components/autocomplete/Autocomplete.stories.tsx
- src/components/autocomplete/Autocomplete.tsx
- src/components/autocomplete/Autocomplete.types.ts
Allows to customize the footer of the autocomplete items popover
> feat: allow to customize autocomplete items footer

- src/components/table/Table.PopoverCell.test.tsx
- src/components/table/Table.PopoverCell.tsx
- src/components/table/Table.PopoverCell.types.ts
- src/components/table/Table.stories.tsx
Allows to customize content for clipboard and for the popover on table popover cell
> MAN-1503: allow to customize content for clipboard and for the popover on table popover cell

- src/components/table/Table.stories.tsx
Foo change to trigger release process once merged
I always forgot about semantic release 🤦
> feat: allow to customize content for clipboard and popover

- src/components/table/Table.HeaderCell.tsx
- src/components/table/Table.stories.tsx
Allow render a menu actions in a header cell at the end of the cell.
> feat: Allow pass a menu actions to the table header

- src/components/toast/ToastProvider.tsx
- src/components/toast/useToasts.ts
fix rerenders in toast component because context is changing in every render
> fix(toast): fix rerenders in toast component

- src/components/toast/ToastProvider.tsx
create portal for toasts container
> fix(toast): create portal for toasts container

- src/components/toast/Toast.tsx
> fix(toast): fix toast icon too small

- src/components/autocomplete/Autocomplete.stories.tsx
- src/components/autocomplete/Autocomplete.test.tsx
- src/components/autocomplete/Autocomplete.tsx
- src/components/autocomplete/Autocomplete.types.ts
Added `disabled` prop to Autocomplete component.
> feat(Autocomplete): add disabled prop

- src/index.ts
Forget to re export the sheet component
> minor: export sheet in the entrypoint

- src/components/sheet/Sheet.styles.ts
The previous PR had a wrong commit name to force a release. Empty commit to force a release
> fix(sheet): fix entrypoint reexport

- src/components/sheet/Sheet.styles.ts
> MAN-1409: minor: only border on the left of sheet component

- src/components/base-spacing/BaseSpacing.test.tsx
- src/components/base-spacing/BaseSpacing.tsx
- src/components/base-spacing/BaseSpacing.types.ts
- src/components/box/Box.tsx
- src/components/box/Box.types.ts
- src/components/typography/Typography.tsx
This MR fixes props from Box and Typography passing to the DOM
> fix(components): fix styled props passing to dom

- src/components/autocomplete/Autocomplete.tsx
- src/components/autocomplete/Autocomplete.types.ts
Allows to style input on autocomplete componente
> feat: allow to style input on autocomplete

- src/components/select/Select.stories.tsx
- src/components/select/Select.tsx
- src/components/select/Select.types.ts
> MAN-1843: Allow select multiples items, customize the item and don't close after select an option
