- .prettierrc
- rollup.config.js
- configure all dependencies from node_modules as externals in rollup config
https://github.com/landbot-org/lui/compare/rollup-externals?expand=1
Test in box-component branch
Before:
After:
> build(rollup): config libraries from node_modules as externals

- src/Box/types.ts
- src/Typography/types.ts
~According to the rule "Every component extends spacing props"~ As Box and Typography accepts spacing props, types now extend BaseSpacingProps to allow the usage of spacing props.
> fix: types extend base spacing

- .storybook/preview.cjs
- src/Button/Button.stories.tsx
- src/Button/Button.styles.ts
- src/Button/Button.test.tsx
- src/Button/Button.tsx
- src/Button/constants.ts
- src/Button/types.ts
- src/Button/utils.ts
- src/Toggle/Toggle.stories.tsx
- src/shared/palette.ts
- src/shared/theme.ts
- src/shared/theme.types.ts
API:
<html>
<body>
Name | Type | Default | Description
-- | -- | -- | --
children | string |   | The button text
color | 'pink.main’ \| ‘blue.main’ \| ‘purple.main’ | 'pink.main' | The button color
disabled | bool | false | If true, the component is disabled.
fullWidth | bool | false | If true, the button will take up the full width of its container.
href | string |   | The URL to link to when the button is clicked. If defined, an a element will be used as the root node.
size | 'small' \| 'medium' \| 'large' | 'medium'  | The button size
variant | 'contained' \| 'outlined' \| 'text' | 'contained' | The button variant
</body>
</html>
> feat(Button): add button component

- .husky/commit-msg
- .husky/pre-commit
- .lintstagedrc.json
- commitlint.config.cjs
- package-lock.json
- package.json
Adds support for husky, lint-staged and commitlint.
This will prevent mistakes in the commit messages that do not follow commitlint rules (which would prevent making a release since they won't trigger semantic release)
It also executes `eslint` before making the commit.
> feat: add husky, lint-staged and commitlint

- commitlint.config.cjs
This rule is not compatible with commits generated by semantic release.
Semantic release example:
Error example:
```
stderr: '\x1B[34m→\x1B[39m No staged files match any configured task.\n' +
'⧗   input: chore(release): 1.17.0 [skip ci]\n' +
'\n' +
'* add husky, lint-staged and commitlint ([f2ef008](https://github.com/landbot-org/lui/commit/f2ef00867a253e11366dcf118428fae8734ce0d5))\n' +
"✖   body's lines must not be longer than 100 characters [body-max-line-length]\n" +
'\n' +
'✖   found 1 problems, 0 warnings\n' +
'ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint\n' +
'\n' +
'husky - commit-msg hook exited with code 1 (error)',
```
> fix: disable body-max-line-length rule for commitlint

- src/Typography/constants.ts
Sets letter-spacing to 0 for `text10` typography variant
> fix: set letter-spacing to 0 for text10 typography variant

- src/Tabs/Tabs.styles.ts
- src/Tabs/Tabs.tsx
If `showScrollButtons` is `false` and `showBottomLine` is `true`, when going from a tab to a previous tab, it shows a weird trailing effect. By setting the `height` of the container to `48px` this issue is resolved.
[Storybook link with current issue](https://638dbcc7869db28ad2ebd96d-crvxmrpoul.chromatic.com/)
[Storybook link with issue fixed generated by this PR](https://638dbcc7869db28ad2ebd96d-vcghjdwrsy.chromatic.com/)
> fix(Tabs): fixes tab indicator

- src/TextArea/TextArea.tsx
- src/TextArea/types.ts
- add forwardRef to interact with textarea from outside, for example, get the position of the cursor and add a string in a this specific position
- Change props typing to TextArea attributes. rows props was not working
> fix(textarea): add forwardref and fix props typing

- src/Button/Button.stories.tsx
- src/Button/Button.styles.ts
- src/Button/Button.tsx
- src/Button/types.ts
* Fixes icons position when full width button. Icons are placed in the start and the end of the button length, not in the middle.
* Added `textAlign` prop to set the position of the text when full width button.
> feat(Button): text alignment prop

- package.json
- src/Popover/Popover.stories.tsx
- src/Popover/Popover.test.tsx
- src/Popover/Popover.tsx
- src/Popover/PopoverClose.tsx
- src/Popover/PopoverContent.tsx
- src/Popover/PopoverContext.tsx
- src/Popover/PopoverTrigger.tsx
- src/Popover/index.ts
- src/Popover/types.ts
- src/Popover/usePopover.ts
- src/Tooltip/Tooltip.test.tsx
- src/index.ts
- src/test-utils/helpers/index.ts
- src/test-utils/helpers/mockResizeObserver.ts
- src/test-utils/index.ts
- src/test-utils/mocks/ResizeObserver.tsx
- src/test-utils/mocks/index.ts
- src/test-utils/render.tsx
- `<Popover>` es el padre que lo envuelve todo
- `<PopoverTrigger>` es el botón que abrirá el popover. Básicamente un button con children
- `<PopoverContent>`  contiene el componente a mostrar cuando esté abierto
- `<PopoverClose>` es el botón para cerrar. Al igual que antes un botón con children. Este es opcional no hace falta ponerlo
También tenemos una propiedad  `preventClose` para especificar si queremos que permanezca abierto al hacer click fuera del popover.
Se basa en el ejemplo [de la docu](https://floating-ui.com/docs/popover#reusable-popover-component)
**IMPORTANTE**: Querido reviewer, si levantas storybook, ten en cuenta que algunas de las properties están puestas a pincho. Así que aunque storybook the ofrece cambiarlas, pues básicamente ,no puedes. 😅
> feat: add popover component

- src/Popover/PopoverContent.tsx
Parece que hay un bug cuando intentamos customizar los estilos.
Les he abierto [un ticket en su github](https://github.com/floating-ui/floating-ui/issues/2378) Por no repetir el problema, lo tenéis en el link.
Esto es simplemente un workaround mientras responden para no bloquearme
> feat: add zIndex

- src/shared/palette.ts
Add color orange 100 (#FFE0A9):
> feat(Shared): add orange 100 (#FFE0A9) color

- src/Tabs/Tabs.stories.tsx
- src/Tabs/Tabs.test.tsx
- src/Tabs/Tabs.tsx
We need to integrate the tabs control in our sidebar; we need to manage the active tab from the sidebar or other external effects.
For that reason, after an analysis, improving the Tab control to give this capacity is a quick win.
> fix(Tabs): allow the active tab management from the outside

- src/TextField/TextField.styles.ts
- src/TextField/types.ts
- src/shared/inputStyles.ts
We allow null as posible value, to be consistent with `null` initializations h[ere](https://git.yexir.com/landbot/landbot/-/commit/062355bf71192bca699339c40ebe85187f841c36)
> feat: allow null as value

- src/Icon/Icon.stories.tsx
* Unified list of icons story into one. All icons are added automatically to the list.
* When clicking an Icon, the component string is copied into clipboard (e.g. `<Calendly />`)
* List of icons are presented alphabetically in a grid with a greater size so they can be easily identified.
> fix: improve Icon storybook

- src/components/icon/icons/WhatsApp.tsx
- src/components/icon/icons/index.ts
- src/components/stepper/Stepper.stories.tsx
Rename the WhatsApp icon by WhatsApp icon, following the strategy of generating a breaking change in the library
> TT-178: rename WhatsApp icon

- package.json
BREAKING CHANGE: changes in peerdependencies
We are using features from react 18 like useId hook
> feat(peerDependencies): allow react version greater than or equal to 18

- src/components/rich-text-editor/RichTextEditor.test.tsx
- src/components/rich-text-editor/RichTextEditor.tsx
- src/components/rich-text-editor/RichTextEditor.types.ts
- src/components/rich-text-editor/plugins/OnFocusPlugin.ts
Added optional prop `onFocus` to detect focus events on the `RichTextEditor` component.
> feat: add onFocus prop to RichTextEditor

- src/components/dialog/Dialog.styles.ts
- src/components/dialog/Dialog.types.ts
- src/components/dialog/DialogContent.tsx
- src/components/dialog/useDialog.ts
- src/components/overlay/Overlay.styles.ts
- src/components/overlay/Overlay.tsx
Our Dialog component has 2 problems:
- It does not allow to customize z-index
- It has a discrepancy between de overlay and the content z-index
That provoques cases like this
> fix: dialog overlay z-index

- src/components/autocomplete/AutoCompleteOptions.tsx
- src/components/autocomplete/Autocomplete.tsx
- src/components/autocomplete/Autocomplete.types.ts
Fixes a wrong type from the yesterday PR. 
`AutoCompleteItem` also includes the separator, which cannot be selected.
> fix: replace wrong type on interface

- src/components/autocomplete/AutoCompleteOptions.tsx
Small PR to try to prevent the next warning:
> fix: prevent key property to be provided as spread

- src/components/autocomplete/AutoCompleteOptions.tsx
- src/components/autocomplete/Autocomplete.tsx
- src/components/autocomplete/Autocomplete.types.ts
Allows to customize placement on autocomplete, like on tooltips and popovers.
Also we need a new try to prevent the new error about key. React won't pass `key` to the children, so there is no need, to specify it.
> fix: allow to customize autocomplete placement

- src/components/autocomplete/AutoCompleteOptions.tsx
- src/components/autocomplete/Autocomplete.tsx
- src/components/autocomplete/Autocomplete.types.ts
Previous change added the posibility to use `onBlur` when input loses the focus. However, selecting an element should not trigger onblur or at provide a way for the consumer to decide what need to execute first.
With this PR we reorder the selecting event to `mouseDown` which has a greater priority than `onBlur` and we allow to handle `onFocus` too
> fix: select item with higher priority event

- src/components/autocomplete/Autocomplete.stories.tsx
- src/components/autocomplete/Autocomplete.test.tsx
- src/components/autocomplete/Autocomplete.tsx
- src/components/autocomplete/Autocomplete.types.ts
- src/components/autocomplete/AutocompleteNoResults.tsx
Allows to customize the render for no results on autocomplete component.
> feat: allow custom render for no results on autocomplete

- src/components/button/Button.utils.ts
Fixes disabled color for error variant on buttons.
[Figma](https://www.figma.com/design/04e06uzVIOJzrIBpbcOquL/LUI-Design-System?node-id=886-412&node-type=frame&t=B4zDGD4ImI2SUoUH-0)
> fix: disabled color on error button variant

- src/shared/theme.types.ts
Color is defined, but TS don't.
> fix: typescript missing value

- src/components/box/Box.constants.ts
Ila notice that the shadows used on the level 2 of elevation doesn't match with the figma.
> MAN-1433: Match shadow from level 2 to the figma shadow values 

- src/components/autocomplete/Autocomplete.test.tsx
- src/components/autocomplete/Autocomplete.tsx
- src/components/autocomplete/Autocomplete.types.ts
I need to easy click between a group of combobox, like the following image:
The current implementation doesn't allow me create specific label, and all the combobox have the same placeholder. On top of that, the select doesn't have a label so the text is going go be hidden visually. Adding this aria give us two benefits
- Tests: I don't need to create a specific HTML selector to click a specific combobox.
- A11y: As a side effect the selects have a semantic view for screen readers.
> MAN-1294: Allow pass aria-labelledby to have better test selector and a11y

- src/components/table/Table.BodySkeleton.tsx
- src/components/table/Table.stories.tsx
Allows to customize skeleton cell size in the same way we do with regular rows.
> feat: allow to customize skeleton sizes on table component

- src/components/popover/Popover.types.ts
- src/components/popover/PopoverContent.tsx
When we use Popover in conjuction with Menu a double border appears. This PR remove the border that have by default PopoverContent. For the situation this doesn't apply you can set a border value
> feat: Set but default a 0 border for popover content while allowing to set it in case it's needed it

- jest.config.cjs
- package-lock.json
- package.json
- src/components/dialog/Dialog.stories.tsx
- src/components/table/Table.PopoverCell.test.tsx
- src/components/table/Table.PopoverCell.tsx
- src/components/table/Table.Row.test.tsx
- tsconfig.json
Updated `@testing-library` packages and `@floating-ui/react` to fix some warnings that appear at every test using the Toast component or corresponding provider.
> fix: clean toast warnings on tests

- src/components/select/Select.test.tsx
- src/components/select/Select.tsx
Remove key property being spread into floating-ui property rather than on the element directly on select component. This fix was already applied on other Dialog, Popover and Autocomplete component, but Select was missing.
Also it prrevents next warnings on tests:
> fix: remove key attribute beign spread

- src/components/autocomplete/Autocomplete.stories.tsx
- src/components/autocomplete/Autocomplete.test.tsx
- src/components/autocomplete/Autocomplete.tsx
- src/components/autocomplete/Autocomplete.types.ts
- src/components/menu/Menu.tsx
- src/components/menu/MenuButton.tsx
- src/components/text-area/TextArea.tsx
Added some improvements for components:
* Set role `menu` for better accessibility.
* Set role `menuitem` for better accessibility.
* Uses automatic id if not provided for better accessibility.
* Added props `label`, `description`, `error` and `helperText` to unify input groups layouts.
> feat: accessibility and inputs improvements

- src/components/menu/Menu.styles.ts
- src/components/popover/Popover.styles.tsx
- src/components/popover/PopoverContent.tsx
* `PopoverContent` border color from `neutral[300]` to `neutral[200]`.
* Background color and border radius from the Menu component, since these properties are already handled by its wrapper (usually PopoverContent).
> feat: update popovercontent border color
